In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
example_data= np.random.randn(5,3)
example_data

array([[ 0.63498476,  0.99088119, -1.82320192],
       [ 0.28272441, -1.77539133, -2.17636095],
       [ 0.38436306,  0.29406158, -0.30549343],
       [-0.88324898,  0.55314412,  0.86802951],
       [-0.11937549,  0.53817934,  0.51112201]])

In [4]:
example_dataframe=pd.DataFrame(example_data)

In [5]:
print(example_dataframe)

          0         1         2
0  0.634985  0.990881 -1.823202
1  0.282724 -1.775391 -2.176361
2  0.384363  0.294062 -0.305493
3 -0.883249  0.553144  0.868030
4 -0.119375  0.538179  0.511122

In [6]:
type(example_dataframe)

pandas.core.frame.DataFrame

In [7]:
print(example_dataframe[0])

0    0.634985
1    0.282724
2    0.384363
3   -0.883249
4   -0.119375
Name: 0, dtype: float64

In [8]:
type(example_dataframe[0])

pandas.core.series.Series

In [9]:
new_df = pd.DataFrame(example_data, index= ["Ali","Ömer","Yusuf","Cennet","Furkan"], columns= ["Price","Age","Seniorty"])
new_df

           Price       Age  Seniorty
Ali     0.634985  0.990881 -1.823202
Ömer    0.282724 -1.775391 -2.176361
Yusuf   0.384363  0.294062 -0.305493
Cennet -0.883249  0.553144  0.868030
Furkan -0.119375  0.538179  0.511122

In [10]:
print(new_df["Age"])

Ali       0.990881
Ömer     -1.775391
Yusuf     0.294062
Cennet    0.553144
Furkan    0.538179
Name: Age, dtype: float64

In [11]:
print(new_df["Seniorty"])

Ali      -1.823202
Ömer     -2.176361
Yusuf    -0.305493
Cennet    0.868030
Furkan    0.511122
Name: Seniorty, dtype: float64

In [12]:
print(new_df[["Age","Price"]])

             Age     Price
Ali     0.990881  0.634985
Ömer   -1.775391  0.282724
Yusuf   0.294062  0.384363
Cennet  0.553144 -0.883249
Furkan  0.538179 -0.119375

In [13]:
print(new_df.loc["Ömer"])

Price       0.282724
Age        -1.775391
Seniorty   -2.176361
Name: Ömer, dtype: float64

In [14]:
print(new_df.loc["Cennet"])

Price      -0.883249
Age         0.553144
Seniorty    0.868030
Name: Cennet, dtype: float64

In [15]:
print(new_df.iloc[4])

Price      -0.119375
Age         0.538179
Seniorty    0.511122
Name: Furkan, dtype: float64

In [16]:
print(new_df.iloc[2])

Price       0.384363
Age         0.294062
Seniorty   -0.305493
Name: Yusuf, dtype: float64

In [17]:
#: tüm satırları seçer sonraki sayı ise istenilen indexteki kolonu getirir.
print(new_df.iloc[:,2])

Ali      -1.823202
Ömer     -2.176361
Yusuf    -0.305493
Cennet    0.868030
Furkan    0.511122
Name: Seniorty, dtype: float64

In [18]:
new_df["Example"]=10

In [19]:
new_df

           Price       Age  Seniorty  Example
Ali     0.634985  0.990881 -1.823202       10
Ömer    0.282724 -1.775391 -2.176361       10
Yusuf   0.384363  0.294062 -0.305493       10
Cennet -0.883249  0.553144  0.868030       10
Furkan -0.119375  0.538179  0.511122       10

In [22]:
new_df["Exampe"]=20

In [23]:
new_df.drop("Exampe" ,axis= 1)

           Price       Age  Seniorty  Example
Ali     0.634985  0.990881 -1.823202       10
Ömer    0.282724 -1.775391 -2.176361       10
Yusuf   0.384363  0.294062 -0.305493       10
Cennet -0.883249  0.553144  0.868030       10
Furkan -0.119375  0.538179  0.511122       10

In [24]:
new_df

           Price       Age  Seniorty  Example  Exampe
Ali     0.634985  0.990881 -1.823202       10      20
Ömer    0.282724 -1.775391 -2.176361       10      20
Yusuf   0.384363  0.294062 -0.305493       10      20
Cennet -0.883249  0.553144  0.868030       10      20
Furkan -0.119375  0.538179  0.511122       10      20

In [25]:
new_df.drop("Exampe", axis=1,inplace=True)

In [26]:
new_df

           Price       Age  Seniorty  Example
Ali     0.634985  0.990881 -1.823202       10
Ömer    0.282724 -1.775391 -2.176361       10
Yusuf   0.384363  0.294062 -0.305493       10
Cennet -0.883249  0.553144  0.868030       10
Furkan -0.119375  0.538179  0.511122       10

In [27]:
new_df["Cennet"]=10

In [28]:
new_df

           Price       Age  Seniorty  Example  Cennet
Ali     0.634985  0.990881 -1.823202       10      10
Ömer    0.282724 -1.775391 -2.176361       10      10
Yusuf   0.384363  0.294062 -0.305493       10      10
Cennet -0.883249  0.553144  0.868030       10      10
Furkan -0.119375  0.538179  0.511122       10      10

In [29]:
new_df.drop("Cennet",axis=1,inplace=True)

In [30]:
new_df

           Price       Age  Seniorty  Example
Ali     0.634985  0.990881 -1.823202       10
Ömer    0.282724 -1.775391 -2.176361       10
Yusuf   0.384363  0.294062 -0.305493       10
Cennet -0.883249  0.553144  0.868030       10
Furkan -0.119375  0.538179  0.511122       10

In [31]:
new_df.drop("Ali",axis=0)

           Price       Age  Seniorty  Example
Ömer    0.282724 -1.775391 -2.176361       10
Yusuf   0.384363  0.294062 -0.305493       10
Cennet -0.883249  0.553144  0.868030       10
Furkan -0.119375  0.538179  0.511122       10

In [32]:
new_df.loc["Ömer","Price"]

np.float64(0.28272441014008254)

In [33]:
new_df.loc["Ömer","Price"]=200

In [34]:
new_df

             Price       Age  Seniorty  Example
Ali       0.634985  0.990881 -1.823202       10
Ömer    200.000000 -1.775391 -2.176361       10
Yusuf     0.384363  0.294062 -0.305493       10
Cennet   -0.883249  0.553144  0.868030       10
Furkan   -0.119375  0.538179  0.511122       10

In [35]:
new_df[new_df>0]

             Price       Age  Seniorty  Example
Ali       0.634985  0.990881       NaN       10
Ömer    200.000000       NaN       NaN       10
Yusuf     0.384363  0.294062       NaN       10
Cennet         NaN  0.553144  0.868030       10
Furkan         NaN  0.538179  0.511122       10

In [36]:
new_df[new_df["Price"]>1]

      Price       Age  Seniorty  Example
Ömer  200.0 -1.775391 -2.176361       10

In [37]:
new_df[new_df["Age"]<0]

      Price       Age  Seniorty  Example
Ömer  200.0 -1.775391 -2.176361       10

In [38]:
new_df.reset_index()

    index       Price       Age  Seniorty  Example
0     Ali    0.634985  0.990881 -1.823202       10
1    Ömer  200.000000 -1.775391 -2.176361       10
2   Yusuf    0.384363  0.294062 -0.305493       10
3  Cennet   -0.883249  0.553144  0.868030       10
4  Furkan   -0.119375  0.538179  0.511122       10

In [39]:
new_df.drop("Example", axis= 1 , inplace= True)

In [40]:
new_df

             Price       Age  Seniorty
Ali       0.634985  0.990881 -1.823202
Ömer    200.000000 -1.775391 -2.176361
Yusuf     0.384363  0.294062 -0.305493
Cennet   -0.883249  0.553144  0.868030
Furkan   -0.119375  0.538179  0.511122

In [41]:
reset_frame=new_df.reset_index()

In [42]:
reset_frame

    index       Price       Age  Seniorty
0     Ali    0.634985  0.990881 -1.823202
1    Ömer  200.000000 -1.775391 -2.176361
2   Yusuf    0.384363  0.294062 -0.305493
3  Cennet   -0.883249  0.553144  0.868030
4  Furkan   -0.119375  0.538179  0.511122

In [43]:
index=["Al","Öm","Yus","Cen","Fur"]
new_df["New İndex"]=index

In [44]:
new_df

             Price       Age  Seniorty New İndex
Ali       0.634985  0.990881 -1.823202        Al
Ömer    200.000000 -1.775391 -2.176361        Öm
Yusuf     0.384363  0.294062 -0.305493       Yus
Cennet   -0.883249  0.553144  0.868030       Cen
Furkan   -0.119375  0.538179  0.511122       Fur

In [45]:
new_df.set_index("New İndex" ,inplace=True)

In [46]:
new_df

                Price       Age  Seniorty
New İndex
Al           0.634985  0.990881 -1.823202
Öm         200.000000 -1.775391 -2.176361
Yus          0.384363  0.294062 -0.305493
Cen         -0.883249  0.553144  0.868030
Fur         -0.119375  0.538179  0.511122

In [47]:
new_df.loc["Öm"]

Price       200.000000
Age          -1.775391
Seniorty     -2.176361
Name: Öm, dtype: float64

In [49]:
#multi index

In [50]:
new_index=["Simpson","Simpson","Simpson","South Park","South Park","South Park"]

In [51]:
inner_index=["Homer","Barge","Merge","Cartman","Kany","Kylie"]

In [52]:
zipped_index=list(zip(new_index , inner_index))

In [53]:
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Barge'),
 ('Simpson', 'Merge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kany'),
 ('South Park', 'Kylie')]

In [54]:
zipped_index=pd.MultiIndex.from_tuples(zipped_index)

In [55]:
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',   'Barge'),
            (   'Simpson',   'Merge'),
            ('South Park', 'Cartman'),
            ('South Park',    'Kany'),
            ('South Park',   'Kylie')],
           )

In [56]:
sample_values=np.ones((6,2))

In [57]:
big_df=pd.DataFrame(sample_values , index=zipped_index, columns=["Age","Salary"])

In [58]:
big_df

                    Age  Salary
Simpson    Homer    1.0     1.0
           Barge    1.0     1.0
           Merge    1.0     1.0
South Park Cartman  1.0     1.0
           Kany     1.0     1.0
           Kylie    1.0     1.0

In [59]:
big_df.loc["Simpson"]

       Age  Salary
Homer  1.0     1.0
Barge  1.0     1.0
Merge  1.0     1.0

In [60]:
big_df.loc["South Park"].loc["Kylie"]

Age       1.0
Salary    1.0
Name: Kylie, dtype: float64

In [61]:
big_df.loc["Simpson"].loc["Merge"]

Age       1.0
Salary    1.0
Name: Merge, dtype: float64