In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
example_data= np.random.randn(5,3)
example_data

array([[ 0.70361797, -1.01023179, -0.51696775],
       [-0.86506675, -1.05545834, -0.19713627],
       [ 0.97498048,  1.18010518,  0.17214392],
       [-0.82917885, -0.83733687, -0.42293822],
       [-1.74960315, -0.43675497, -0.96073219]])

In [4]:
example_dataframe=pd.DataFrame(example_data)

In [5]:
print(example_dataframe)

          0         1         2
0  0.703618 -1.010232 -0.516968
1 -0.865067 -1.055458 -0.197136
2  0.974980  1.180105  0.172144
3 -0.829179 -0.837337 -0.422938
4 -1.749603 -0.436755 -0.960732

In [6]:
type(example_dataframe)

pandas.core.frame.DataFrame

In [7]:
print(example_dataframe[0])

0    0.703618
1   -0.865067
2    0.974980
3   -0.829179
4   -1.749603
Name: 0, dtype: float64

In [8]:
type(example_dataframe[0])

pandas.core.series.Series

In [9]:
new_df = pd.DataFrame(example_data, index= ["Ali","Ömer","Yusuf","Cennet","Furkan"], columns= ["Price","Age","Seniorty"])
new_df

           Price       Age  Seniorty
Ali     0.703618 -1.010232 -0.516968
Ömer   -0.865067 -1.055458 -0.197136
Yusuf   0.974980  1.180105  0.172144
Cennet -0.829179 -0.837337 -0.422938
Furkan -1.749603 -0.436755 -0.960732

In [10]:
print(new_df["Age"])

Ali      -1.010232
Ömer     -1.055458
Yusuf     1.180105
Cennet   -0.837337
Furkan   -0.436755
Name: Age, dtype: float64

In [11]:
print(new_df["Seniorty"])

Ali      -0.516968
Ömer     -0.197136
Yusuf     0.172144
Cennet   -0.422938
Furkan   -0.960732
Name: Seniorty, dtype: float64

In [12]:
print(new_df[["Age","Price"]])

             Age     Price
Ali    -1.010232  0.703618
Ömer   -1.055458 -0.865067
Yusuf   1.180105  0.974980
Cennet -0.837337 -0.829179
Furkan -0.436755 -1.749603

In [13]:
print(new_df.loc["Ömer"])

Price      -0.865067
Age        -1.055458
Seniorty   -0.197136
Name: Ömer, dtype: float64

In [14]:
print(new_df.loc["Cennet"])

Price      -0.829179
Age        -0.837337
Seniorty   -0.422938
Name: Cennet, dtype: float64

In [15]:
print(new_df.iloc[4])

Price      -1.749603
Age        -0.436755
Seniorty   -0.960732
Name: Furkan, dtype: float64

In [16]:
#: tüm satırları seçer sonraki sayı ise istenilen indexteki kolonu getirir.
print(new_df.iloc[:,2])

Ali      -0.516968
Ömer     -0.197136
Yusuf     0.172144
Cennet   -0.422938
Furkan   -0.960732
Name: Seniorty, dtype: float64

In [20]:
new_df["Example"]=10

In [21]:
new_df

           Price       Age  Seniorty  Exampe  Example
Ali     0.703618 -1.010232 -0.516968      10       10
Ömer   -0.865067 -1.055458 -0.197136      10       10
Yusuf   0.974980  1.180105  0.172144      10       10
Cennet -0.829179 -0.837337 -0.422938      10       10
Furkan -1.749603 -0.436755 -0.960732      10       10

In [24]:
new_df.drop("Exampe" ,axis= 1)

           Price       Age  Seniorty  Example
Ali     0.703618 -1.010232 -0.516968       10
Ömer   -0.865067 -1.055458 -0.197136       10
Yusuf   0.974980  1.180105  0.172144       10
Cennet -0.829179 -0.837337 -0.422938       10
Furkan -1.749603 -0.436755 -0.960732       10

In [25]:
new_df

           Price       Age  Seniorty  Exampe  Example
Ali     0.703618 -1.010232 -0.516968      10       10
Ömer   -0.865067 -1.055458 -0.197136      10       10
Yusuf   0.974980  1.180105  0.172144      10       10
Cennet -0.829179 -0.837337 -0.422938      10       10
Furkan -1.749603 -0.436755 -0.960732      10       10

In [26]:
new_df.drop("Exampe", axis=1,inplace=True)

In [27]:
new_df

           Price       Age  Seniorty  Example
Ali     0.703618 -1.010232 -0.516968       10
Ömer   -0.865067 -1.055458 -0.197136       10
Yusuf   0.974980  1.180105  0.172144       10
Cennet -0.829179 -0.837337 -0.422938       10
Furkan -1.749603 -0.436755 -0.960732       10

In [33]:
new_df["Cennet"]=10

In [35]:
new_df

           Price       Age  Seniorty  Example  Cennet
Ali     0.703618 -1.010232 -0.516968       10      10
Ömer   -0.865067 -1.055458 -0.197136       10      10
Yusuf   0.974980  1.180105  0.172144       10      10
Cennet -0.829179 -0.837337 -0.422938       10      10
Furkan -1.749603 -0.436755 -0.960732       10      10

In [38]:
new_df.drop("Cennet",axis=1,inplace=True)

In [39]:
new_df

           Price       Age  Seniorty  Example
Ali     0.703618 -1.010232 -0.516968       10
Ömer   -0.865067 -1.055458 -0.197136       10
Yusuf   0.974980  1.180105  0.172144       10
Cennet -0.829179 -0.837337 -0.422938       10
Furkan -1.749603 -0.436755 -0.960732       10

In [40]:
new_df.drop("Ali",axis=0)

           Price       Age  Seniorty  Example
Ömer   -0.865067 -1.055458 -0.197136       10
Yusuf   0.974980  1.180105  0.172144       10
Cennet -0.829179 -0.837337 -0.422938       10
Furkan -1.749603 -0.436755 -0.960732       10

In [42]:
new_df.loc["Ömer","Price"]

np.float64(-0.8650667535887504)

In [43]:
new_df.loc["Ömer","Price"]=200

In [44]:
new_df

             Price       Age  Seniorty  Example
Ali       0.703618 -1.010232 -0.516968       10
Ömer    200.000000 -1.055458 -0.197136       10
Yusuf     0.974980  1.180105  0.172144       10
Cennet   -0.829179 -0.837337 -0.422938       10
Furkan   -1.749603 -0.436755 -0.960732       10

In [45]:
new_df[new_df>0]

             Price       Age  Seniorty  Example
Ali       0.703618       NaN       NaN       10
Ömer    200.000000       NaN       NaN       10
Yusuf     0.974980  1.180105  0.172144       10
Cennet         NaN       NaN       NaN       10
Furkan         NaN       NaN       NaN       10

In [47]:
new_df[new_df["Price"]>1]

      Price       Age  Seniorty  Example
Ömer  200.0 -1.055458 -0.197136       10

In [49]:
new_df[new_df["Age"]<0]

             Price       Age  Seniorty  Example
Ali       0.703618 -1.010232 -0.516968       10
Ömer    200.000000 -1.055458 -0.197136       10
Cennet   -0.829179 -0.837337 -0.422938       10
Furkan   -1.749603 -0.436755 -0.960732       10