In [1]:
import pandas as pd

In [2]:
df_apply= pd.read_csv("8-apply_function_data.csv")

In [3]:
df_apply

    Employee_ID     Name Department  Salary  Experience  Performance_Score
0             1    Emp_1  Marketing   82251           6                  5
1             2    Emp_2      Sales   52662          24                  3
2             3    Emp_3    Finance   38392           5                  3
3             4    Emp_4      Sales   60535          20                  3
4             5    Emp_5      Sales  108603           2                  2
..          ...      ...        ...     ...         ...                ...
95           96   Emp_96    Finance   93734          19                  4
96           97   Emp_97      Sales  100467          22                  2
97           98   Emp_98         IT   82662          23                  3
98           99   Emp_99         IT   42688          22                  1
99          100  Emp_100         HR   55342          14                  3

[100 rows x 6 columns]

In [4]:
df_apply.head()

   Employee_ID   Name Department  Salary  Experience  Performance_Score
0            1  Emp_1  Marketing   82251           6                  5
1            2  Emp_2      Sales   52662          24                  3
2            3  Emp_3    Finance   38392           5                  3
3            4  Emp_4      Sales   60535          20                  3
4            5  Emp_5      Sales  108603           2                  2

In [5]:
df_apply.describe()

       Employee_ID         Salary  Experience  Performance_Score
count   100.000000     100.000000  100.000000          100.00000
mean     50.500000   77508.090000   12.090000            3.03000
std      29.011492   26083.327596    7.543939            1.41746
min       1.000000   30206.000000    1.000000            1.00000
25%      25.750000   54347.500000    5.000000            2.00000
50%      50.500000   80932.000000   12.000000            3.00000
75%      75.250000   97620.500000   19.000000            4.00000
max     100.000000  119474.000000   24.000000            5.00000

In [6]:
df_apply.tail()

    Employee_ID     Name Department  Salary  Experience  Performance_Score
95           96   Emp_96    Finance   93734          19                  4
96           97   Emp_97      Sales  100467          22                  2
97           98   Emp_98         IT   82662          23                  3
98           99   Emp_99         IT   42688          22                  1
99          100  Emp_100         HR   55342          14                  3

In [7]:
df_apply["Experience"].count()

np.int64(100)

In [8]:
df_apply["Performance_Score"].max()

5

In [9]:
df_apply.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        100 non-null    int64
 1   Name               100 non-null    object
 2   Department         100 non-null    object
 3   Salary             100 non-null    int64
 4   Experience         100 non-null    int64
 5   Performance_Score  100 non-null    int64
dtypes: int64(4), object(2)
memory usage: 4.8+ KB

In [10]:
df_apply.columns

Index(['Employee_ID', 'Name', 'Department', 'Salary', 'Experience',
       'Performance_Score'],
      dtype='object')

In [11]:
df_apply[1:20]

    Employee_ID    Name Department  Salary  Experience  Performance_Score
1             2   Emp_2      Sales   52662          24                  3
2             3   Emp_3    Finance   38392           5                  3
3             4   Emp_4      Sales   60535          20                  3
4             5   Emp_5      Sales  108603           2                  2
5             6   Emp_6         IT   82256           6                  5
6             7   Emp_7    Finance  119135          22                  1
7             8   Emp_8    Finance   65222          11                  4
8             9   Emp_9    Finance  107373          16                  1
9            10  Emp_10      Sales  109575          16                  5
10           11  Emp_11  Marketing  114651           1                  4
11           12  Emp_12    Finance   93335           9                  5
12           13  Emp_13      Sales   40965           6                  3
13           14  Emp_14         IT   54538          16                  4
14           15  Emp_15  Marketing  100592           3                  3
15           16  Emp_16         IT   38110          20                  1
16           17  Emp_17  Marketing  109309           4                  1
17           18  Emp_18      Sales   57266          19                  4
18           19  Emp_19         HR   82992           3                  4
19           20  Emp_20  Marketing  112948          19                  5

In [12]:
def salary_category(salary):
    if salary <50000:
        return "Low"
    elif 50000<= salary <=80000:
        return "Medium"
    else:
        return "High"

In [13]:
df_apply["Salary_Category"]=df_apply["Salary"].apply(salary_category)

In [14]:
df_apply

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category
0,1,Emp_1,Marketing,82251,6,5,High
1,2,Emp_2,Sales,52662,24,3,Medium
2,3,Emp_3,Finance,38392,5,3,Low
3,4,Emp_4,Sales,60535,20,3,Medium
4,5,Emp_5,Sales,108603,2,2,High
...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High
96,97,Emp_97,Sales,100467,22,2,High
97,98,Emp_98,IT,82662,23,3,High
98,99,Emp_99,IT,42688,22,1,Low
99,100,Emp_100,HR,55342,14,3,Medium

In [15]:

def experience_score(experience):
    if experience >10:
        return 1
    else:
        return 0

In [16]:
df_apply["Adjusted"]=df_apply["Experience"].apply(experience_score)

In [17]:
df_apply

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted
0,1,Emp_1,Marketing,82251,6,5,High,0
1,2,Emp_2,Sales,52662,24,3,Medium,1
2,3,Emp_3,Finance,38392,5,3,Low,0
3,4,Emp_4,Sales,60535,20,3,Medium,1
4,5,Emp_5,Sales,108603,2,2,High,0
...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,1
96,97,Emp_97,Sales,100467,22,2,High,1
97,98,Emp_98,IT,82662,23,3,High,1
98,99,Emp_99,IT,42688,22,1,Low,1
99,100,Emp_100,HR,55342,14,3,Medium,1

In [18]:
df_apply["New Score"]= df_apply["Performance_Score"] + df_apply["Adjusted"]

In [19]:
df_apply

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted,New Score
0,1,Emp_1,Marketing,82251,6,5,High,0,5
1,2,Emp_2,Sales,52662,24,3,Medium,1,4
2,3,Emp_3,Finance,38392,5,3,Low,0,3
3,4,Emp_4,Sales,60535,20,3,Medium,1,4
4,5,Emp_5,Sales,108603,2,2,High,0,2
...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,1,5
96,97,Emp_97,Sales,100467,22,2,High,1,3
97,98,Emp_98,IT,82662,23,3,High,1,4
98,99,Emp_99,IT,42688,22,1,Low,1,2
99,100,Emp_100,HR,55342,14,3,Medium,1,4

In [20]:
def adjusted_score(row):
    if row["Experience"]>10:
        return row ["Performance_Score"]+1
    else:
        return row ["Performance_Score"]

In [21]:
df_apply["Adjusted_Score"]=df_apply.apply(adjusted_score , axis= 1)

In [22]:
df_apply

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted,New Score,Adjusted_Score
0,1,Emp_1,Marketing,82251,6,5,High,0,5,5
1,2,Emp_2,Sales,52662,24,3,Medium,1,4,4
2,3,Emp_3,Finance,38392,5,3,Low,0,3,3
3,4,Emp_4,Sales,60535,20,3,Medium,1,4,4
4,5,Emp_5,Sales,108603,2,2,High,0,2,2
...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,1,5,5
96,97,Emp_97,Sales,100467,22,2,High,1,3,3
97,98,Emp_98,IT,82662,23,3,High,1,4,4
98,99,Emp_99,IT,42688,22,1,Low,1,2,2
99,100,Emp_100,HR,55342,14,3,Medium,1,4,4

In [23]:
df_apply["Formatted_Name"]=df_apply["Name"].apply(lambda x : x.replace("_"," "))

In [24]:
df_apply

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted,New Score,Adjusted_Score,Formatted_Name
0,1,Emp_1,Marketing,82251,6,5,High,0,5,5,Emp 1
1,2,Emp_2,Sales,52662,24,3,Medium,1,4,4,Emp 2
2,3,Emp_3,Finance,38392,5,3,Low,0,3,3,Emp 3
3,4,Emp_4,Sales,60535,20,3,Medium,1,4,4,Emp 4
4,5,Emp_5,Sales,108603,2,2,High,0,2,2,Emp 5
...,...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,1,5,5,Emp 96
96,97,Emp_97,Sales,100467,22,2,High,1,3,3,Emp 97
97,98,Emp_98,IT,82662,23,3,High,1,4,4,Emp 98
98,99,Emp_99,IT,42688,22,1,Low,1,2,2,Emp 99
99,100,Emp_100,HR,55342,14,3,Medium,1,4,4,Emp 100

In [25]:
df_apply.drop("New Score" , axis=1 , inplace=True)

In [26]:
df_apply

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted,Adjusted_Score,Formatted_Name
0,1,Emp_1,Marketing,82251,6,5,High,0,5,Emp 1
1,2,Emp_2,Sales,52662,24,3,Medium,1,4,Emp 2
2,3,Emp_3,Finance,38392,5,3,Low,0,3,Emp 3
3,4,Emp_4,Sales,60535,20,3,Medium,1,4,Emp 4
4,5,Emp_5,Sales,108603,2,2,High,0,2,Emp 5
...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,1,5,Emp 96
96,97,Emp_97,Sales,100467,22,2,High,1,3,Emp 97
97,98,Emp_98,IT,82662,23,3,High,1,4,Emp 98
98,99,Emp_99,IT,42688,22,1,Low,1,2,Emp 99
99,100,Emp_100,HR,55342,14,3,Medium,1,4,Emp 100

In [27]:
df_apply.drop("Adjusted" , axis=1 , inplace=True)

In [28]:
df_apply

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted_Score,Formatted_Name
0,1,Emp_1,Marketing,82251,6,5,High,5,Emp 1
1,2,Emp_2,Sales,52662,24,3,Medium,4,Emp 2
2,3,Emp_3,Finance,38392,5,3,Low,3,Emp 3
3,4,Emp_4,Sales,60535,20,3,Medium,4,Emp 4
4,5,Emp_5,Sales,108603,2,2,High,2,Emp 5
...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,5,Emp 96
96,97,Emp_97,Sales,100467,22,2,High,3,Emp 97
97,98,Emp_98,IT,82662,23,3,High,4,Emp 98
98,99,Emp_99,IT,42688,22,1,Low,2,Emp 99
99,100,Emp_100,HR,55342,14,3,Medium,4,Emp 100

In [29]:
def department_info(row):
    if row["Department"]=="Marketing":
        return row["Salary"]+10000
    elif row["Department"]=="Sales":
        return row["Salary"] +5000
    elif row["Department"]=="IT":
        return row["Salary"] +15000
    else:
        return row["Salary"]

In [30]:
df_apply["New Salary"]=df_apply.apply(department_info , axis=1)

In [31]:
df_apply

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted_Score,Formatted_Name,New Salary
0,1,Emp_1,Marketing,82251,6,5,High,5,Emp 1,92251
1,2,Emp_2,Sales,52662,24,3,Medium,4,Emp 2,57662
2,3,Emp_3,Finance,38392,5,3,Low,3,Emp 3,38392
3,4,Emp_4,Sales,60535,20,3,Medium,4,Emp 4,65535
4,5,Emp_5,Sales,108603,2,2,High,2,Emp 5,113603
...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,5,Emp 96,93734
96,97,Emp_97,Sales,100467,22,2,High,3,Emp 97,105467
97,98,Emp_98,IT,82662,23,3,High,4,Emp 98,97662
98,99,Emp_99,IT,42688,22,1,Low,2,Emp 99,57688
99,100,Emp_100,HR,55342,14,3,Medium,4,Emp 100,55342

In [32]:
def bonus (row):
    if row["Performance_Score"]==5:
        return row["Salary"]+8000
    elif row["Performance_Score"]==4:
        return row["Salary"]+5000
    elif row["Performance_Score"]==3:
        return row["Salary"]+3000
    elif row["Performance_Score"]==2:
        return row["Salary"]+1000
    else:
        return row["Salary"]

In [33]:
df_apply["Bonus"]=df_apply.apply(bonus , axis=1)

In [34]:
df_apply

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted_Score,Formatted_Name,New Salary,Bonus
0,1,Emp_1,Marketing,82251,6,5,High,5,Emp 1,92251,90251
1,2,Emp_2,Sales,52662,24,3,Medium,4,Emp 2,57662,55662
2,3,Emp_3,Finance,38392,5,3,Low,3,Emp 3,38392,41392
3,4,Emp_4,Sales,60535,20,3,Medium,4,Emp 4,65535,63535
4,5,Emp_5,Sales,108603,2,2,High,2,Emp 5,113603,109603
...,...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,5,Emp 96,93734,98734
96,97,Emp_97,Sales,100467,22,2,High,3,Emp 97,105467,101467
97,98,Emp_98,IT,82662,23,3,High,4,Emp 98,97662,85662
98,99,Emp_99,IT,42688,22,1,Low,2,Emp 99,57688,42688
99,100,Emp_100,HR,55342,14,3,Medium,4,Emp 100,55342,58342

In [35]:
df_apply.drop("Salary_Category" , axis=1 , inplace=True)

In [36]:
df_apply

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Adjusted_Score,Formatted_Name,New Salary,Bonus
0,1,Emp_1,Marketing,82251,6,5,5,Emp 1,92251,90251
1,2,Emp_2,Sales,52662,24,3,4,Emp 2,57662,55662
2,3,Emp_3,Finance,38392,5,3,3,Emp 3,38392,41392
3,4,Emp_4,Sales,60535,20,3,4,Emp 4,65535,63535
4,5,Emp_5,Sales,108603,2,2,2,Emp 5,113603,109603
...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,5,Emp 96,93734,98734
96,97,Emp_97,Sales,100467,22,2,3,Emp 97,105467,101467
97,98,Emp_98,IT,82662,23,3,4,Emp 98,97662,85662
98,99,Emp_99,IT,42688,22,1,2,Emp 99,57688,42688
99,100,Emp_100,HR,55342,14,3,4,Emp 100,55342,58342

In [37]:
df_apply.drop("New Salary" ,axis=1 , inplace=True)

In [38]:
df_apply

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Adjusted_Score,Formatted_Name,Bonus
0,1,Emp_1,Marketing,82251,6,5,5,Emp 1,90251
1,2,Emp_2,Sales,52662,24,3,4,Emp 2,55662
2,3,Emp_3,Finance,38392,5,3,3,Emp 3,41392
3,4,Emp_4,Sales,60535,20,3,4,Emp 4,63535
4,5,Emp_5,Sales,108603,2,2,2,Emp 5,109603
...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,5,Emp 96,98734
96,97,Emp_97,Sales,100467,22,2,3,Emp 97,101467
97,98,Emp_98,IT,82662,23,3,4,Emp 98,85662
98,99,Emp_99,IT,42688,22,1,2,Emp 99,42688
99,100,Emp_100,HR,55342,14,3,4,Emp 100,58342

In [47]:
df_apply.drop("Adjusted_Score" ,axis=1 , inplace=True)

KeyError: "['Adjusted_Score'] not found in axis"

In [ ]:
df_apply.drop("Formatted_Name" ,axis=1 , inplace=True)

In [41]:
df_apply

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Bonus
0,1,Emp_1,Marketing,82251,6,5,90251
1,2,Emp_2,Sales,52662,24,3,55662
2,3,Emp_3,Finance,38392,5,3,41392
3,4,Emp_4,Sales,60535,20,3,63535
4,5,Emp_5,Sales,108603,2,2,109603
...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,98734
96,97,Emp_97,Sales,100467,22,2,101467
97,98,Emp_98,IT,82662,23,3,85662
98,99,Emp_99,IT,42688,22,1,42688
99,100,Emp_100,HR,55342,14,3,58342

In [42]:
def employee_level(row):
    if row["Experience"]<=5:
        return "Junior"
    elif row["Experience"]<=15:
        return "Mid"
    elif row["Experience"]>15:
        return "Senior"
    else:
        return "Not Found Experience"

In [50]:
df_apply["Employee_Level"]=df_apply.apply(employee_level , axis=1)

In [51]:
df_apply

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Bonus,Employee_Level,Updated_Salary
0,1,Emp_1,Marketing,82251,6,5,90251,Mid,123376.5
1,2,Emp_2,Sales,52662,24,3,55662,Senior,68460.6
2,3,Emp_3,Finance,38392,5,3,41392,Junior,49909.6
3,4,Emp_4,Sales,60535,20,3,63535,Senior,78695.5
4,5,Emp_5,Sales,108603,2,2,109603,Junior,130323.6
...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,98734,Senior,131227.6
96,97,Emp_97,Sales,100467,22,2,101467,Senior,120560.4
97,98,Emp_98,IT,82662,23,3,85662,Senior,107460.6
98,99,Emp_99,IT,42688,22,1,42688,Senior,46956.8
99,100,Emp_100,HR,55342,14,3,58342,Mid,71944.6

In [44]:


def update_salary (row):
    if row["Performance_Score"]==5:
        return row["Salary"] *1.5
    elif row["Performance_Score"]==4:
        return row["Salary"] * 1.4
    elif row["Performance_Score"]==3:
        return row["Salary"] * 1.3
    elif row["Performance_Score"]==2:
        return row["Salary"] * 1.2
    else:
        return row["Salary"]*1.1

In [45]:
df_apply["Updated_Salary"]=df_apply.apply(update_salary, axis=1)

In [46]:
df_apply

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Bonus,Employee_Level,Updated_Salary
0,1,Emp_1,Marketing,82251,6,5,90251,Mid,123376.5
1,2,Emp_2,Sales,52662,24,3,55662,Senior,68460.6
2,3,Emp_3,Finance,38392,5,3,41392,Junior,49909.6
3,4,Emp_4,Sales,60535,20,3,63535,Senior,78695.5
4,5,Emp_5,Sales,108603,2,2,109603,Junior,130323.6
...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,98734,Senior,131227.6
96,97,Emp_97,Sales,100467,22,2,101467,Senior,120560.4
97,98,Emp_98,IT,82662,23,3,85662,Senior,107460.6
98,99,Emp_99,IT,42688,22,1,42688,Senior,46956.8
99,100,Emp_100,HR,55342,14,3,58342,Mid,71944.6